dictionaries = [
    "en_us",
    "en_gb",
]
words = [
    "autoboxing",
    "bak",
    "bvps",
    "chmod",
    "codebook",
    "compdef",
    "compinit",
    "corepack",
    "cpath",
    "cppflags",
    "cref",
    "cssprop",
    "csunix",
    "ctrls",
    "dasharray",
    "drawio",
    "eps",
    "fpath",
    "fzf",
    "getifaddr",
    "getters",
    "hbar",
    "hgap",
    "histfile",
    "histsize",
    "homebrew",
    "imgs",
    "jans",
    "janssen",
    "jdk",
    "jdt",
    "jenv",
    "jfx",
    "jre",
    "kleene",
    "launchd",
    "leetcode",
    "liberica",
    "libexec",
    "linecap",
    "lukejans",
    "lukes",
    "manpager",
    "minimax",
    "mise",
    "mohawkcollege",
    "mousedown",
    "mousemove",
    "neofetch",
    "nums",
    "nvm",
    "nvmrc",
    "nxt",
    "ogp",
    "oop",
    "openjdk",
    "osascript",
    "plex",
    "pnpm",
    "postcss",
    "preconnect",
    "renderers",
    "rustc",
    "rustfmt",
    "savehist",
    "sed",
    "seo",
    "shellcheck",
    "shellenv",
    "soa",
    "stackexchange",
    "starship",
    "stylelint",
    "supertypes",
    "tmux",
    "trackpad",
    "trustability",
    "uml",
    "uno",
    "vbar",
    "vgap",
    "vite",
    "webmanifest",
    "whatis",
    "xdg",
    "yazi",
    "zprofile",
    "zsh",
    "zshell",
    "zshenv",
    "zshrc",
]
ignore_paths = [
    "target/**/*",
    "**/*.json",
    ".git/**/*",
]
ignore_patterns = [
    "^[ATCG]+$",
    '\d{3}-\d{2}-\d{4}',
]
